### ISSUE TITLE
So many white spaces

### ISSUE THREAD

**Issue by f0ntana** [rishichawda/react-native-qrcode-generator#12]
Hi, i test on my app and has a lot off space i think is the webview, can i resize ?

i use align center and justify center

![Screen Shot 2020-01-24 at 14 57 12](https://user-images.githubusercontent.com/6570783/73095887-ecbe7c80-3eb9-11ea-8b4e-357e1c38fe12.png)

**Comment by rishichawda** [comment]
Hi @f0ntana. The WebView's outer container only wraps it to act as a container and does not enforce any particular dimension to the WebView. Can you please provide a link to an example/demo so that I can take a better look at it?

**Comment by LaksCastro** [comment]
I have the same problem
and I'm using the size property: however it is the blank space that receives the size

**Comment by f0ntana** [comment]
> Hi @f0ntana. The WebView's outer container only wraps it to act as a container and does not enforce any particular dimension to the WebView. Can you please provide a link to an example/demo so that I can take a better look at it?
> 
> There is also a `size` prop on the component that you can try, incase you missed it.

@rishichawda 

i tried but the white space continue.

**Comment by fhugoduarte** [comment]
@rishichawda same issue.
Do you have any solution?

**Comment by rishichawda** [comment]
@LaksCastro @f0ntana @fhugoduarte Sorry about the late response. I haven't had much time lately to take a look at this. I have a long weekend ahead so hopefully a new version will be released in the next couple days to fix this issue. 🤞😃

**Comment by LilaGuill** [comment]
@rishichawda we have the same problem, do you have a solution to fix that ? Thanks you :))

**Comment by cvaca7** [comment]
@rishichawda Any news? I would like to use this package in my project. Thanks for sharing

**Comment by rishichawda** [comment]
Fixed in latest release react-native-qrcode-generator v 1.1.2  🎉 Cheers!
