### ISSUE TITLE
Bad View.

### ISSUE THREAD

**Issue by chamodKanishka** [rishichawda/react-native-qrcode-generator#14]
previously I use react-native-qrcode library to generate my QR codes and its perfectly do its task and view like this and it easialy can scan.
![Screenshot_20200219-203201](https://user-images.githubusercontent.com/38470365/76225455-85c70e00-6242-11ea-9e31-19a476483e53.jpg)

**Comment by chamodKanishka** [comment]
now its look like this with the same things in this library and its very hard to scan qr code
![Screenshot_20200309-201541](https://user-images.githubusercontent.com/38470365/76226227-91ff9b00-6243-11ea-916b-91c74d811f72.jpg)

**Comment by psyzz** [comment]
Same for me, when i set the size i get a qrcode stick to the left part of the view.
Can't center the qrcode

**Comment by rishichawda** [comment]
Fixed in latest release react-native-qrcode-generator [v 1.1.2](https://github.com/rishichawda/react-native-qrcode-generator/releases/tag/v1.1.2)  🎉
