### ISSUE TITLE
Scrollable Bad View

### ISSUE THREAD

**Issue by chamodKanishka** [rishichawda/react-native-qrcode-generator#16]
this error occurs with 1.1.2 version of this

with default size 200

![Screenshot_20200326-201805](https://user-images.githubusercontent.com/38470365/77660988-0a828d80-6fa0-11ea-91ab-50aec006e549.jpg)

**Comment by chamodKanishka** [comment]
![Screenshot_20200326-201817](https://user-images.githubusercontent.com/38470365/77661029-1c643080-6fa0-11ea-99a2-caaf944ec809.jpg) scrollble bad view

**Comment by rishichawda** [comment]
@chamodKanishka I'm sorry but I can't help you with just screenshots. Perhaps, you can try and reproduce this in a sandbox or show the code here? Thanks!

**Comment by rishichawda** [comment]
@chamodKanishka I'm sorry but I might not be able to help you with just screenshots. Perhaps, you can try and reproduce this in a sandbox or show the code here? Thanks!

**Comment by chamodKanishka** [comment]
Qr code can be scroll. but it cant be undone. thats why i use that title :).

**Comment by chamodKanishka** [comment]
<QRCode
          value={this.state.text}
          size={200}
          bgColor='black'
          fgColor='white'/>

this is the code. I remove that text input field. because it unnecessary to me

**Comment by chamodKanishka** [comment]
`<QRCode
          value={this.state.text}
          size={200}
          bgColor='black'
          fgColor='white'/>`

this is the code that I used. I removed text input filed because it unnecessary to me

**Comment by rishichawda** [comment]
@chamodKanishka Looks like you tried to zoom the code and then scroll. Please install [latest version v1.2.0](https://github.com/rishichawda/react-native-qrcode-generator/releases/tag/v1.2.0) of the package from npm and it should not allow you to do that now. Cheers! 🎉
