### ISSUE TITLE
getImageOnLoad doesn't work

### ISSUE THREAD

**Issue by MaksZhukov** [rishichawda/react-native-qrcode-generator#18]
getImageOnLoad prop doesn't work

**Comment by rishichawda** [comment]
Hi @MaksZhukov, It looks like I forgot to refactor the postMessage call in the last release. Sorry about that! You can try out the latest release v1.2.1 and it should work.

**Comment by MaksZhukov** [comment]
Hi @rishichawda, ok, thank you!
